// pdfGenerator.js — build an 8.5x11" receipt PDF with jsPDF.
// Returns { blob, filename }. Photo scaled to fit, parsed data below it.

import { jsPDF } from "jspdf";

const PAGE_W = 8.5;
const PAGE_H = 11;
const MARGIN = 0.75;
const CONTENT_W = PAGE_W - MARGIN * 2; // 7"

export function generateReceiptPdf(receipt, imageDataUrl) {
  const doc = new jsPDF({ unit: "in", format: "letter" });

  // ---- Header ----
  doc.setFont("times", "bold");
  doc.setFontSize(20);
  doc.setTextColor(20, 17, 14);
  doc.text("Business Expense Receipt", MARGIN, MARGIN + 0.1);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(130, 122, 110);
  doc.text("Ledger — Receipt Tracker", MARGIN, MARGIN + 0.4);

  // hairline
  doc.setDrawColor(200, 192, 180);
  doc.setLineWidth(0.01);
  doc.line(MARGIN, MARGIN + 0.55, PAGE_W - MARGIN, MARGIN + 0.55);

  // ---- Photo (scaled to fit, max ~6" wide, centered) ----
  let cursorY = MARGIN + 0.85;
  if (imageDataUrl) {
    const props = doc.getImageProperties(imageDataUrl);
    const maxW = Math.min(6, CONTENT_W);
    const maxH = 6.0;
    let w = maxW;
    let h = (props.height / props.width) * w;
    if (h > maxH) {
      h = maxH;
      w = (props.width / props.height) * h;
    }
    const x = (PAGE_W - w) / 2;
    doc.addImage(imageDataUrl, "JPEG", x, cursorY, w, h);
    cursorY += h + 0.45;
  }

  // ---- Data table ----
  const rows = [
    ["Merchant", receipt.merchant || "—"],
    ["Date", receipt.date || "—"],
    ["Amount", "$" + (Number(receipt.amount) || 0).toFixed(2)],
    ["Category", receipt.category || "—"],
    ["Description", receipt.description || "—"],
  ];

  doc.setFontSize(11);
  const labelX = MARGIN;
  const valueX = MARGIN + 1.6;
  const rowH = 0.32;

  rows.forEach(([label, value], i) => {
    const y = cursorY + i * rowH;
    // zebra background
    if (i % 2 === 0) {
      doc.setFillColor(245, 242, 236);
      doc.rect(MARGIN, y - 0.22, CONTENT_W, rowH, "F");
    }
    doc.setFont("helvetica", "bold");
    doc.setTextColor(110, 101, 90);
    doc.text(label, labelX + 0.05, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(20, 17, 14);
    const wrapped = doc.splitTextToSize(String(value), CONTENT_W - 1.7);
    doc.text(wrapped, valueX, y);
  });

  // ---- Footer ----
  const stamp = new Date().toLocaleString("en-US");
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(150, 142, 130);
  doc.text(`Generated by Ledger on ${stamp}`, MARGIN, PAGE_H - 0.5);

  const blob = doc.output("blob");
  const filename = buildFilename(receipt);
  return { blob, filename };
}

function buildFilename(receipt) {
  const date = receipt.date || new Date().toISOString().slice(0, 10);
  const merchant = (receipt.merchant || "receipt")
    .replace(/[^a-z0-9]+/gi, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 40);
  return `receipt_${date}_${merchant}.pdf`;
}
